version: "3"
services:
  registry:
    image: registry
    container_name: registry
    #restart: always
    volumes:
      - "/usr/local/var/registry:/var/lib/registry"
      - "./etc/registry/config.yml:/etc/docker/registry/config.yml"
    ports:
      - "5000:5000"
networks: 
  default:
    external:
      name: dockerdevelop_default