php:
  image: 'fatrbaby/php7'
  volumes:
    - '/usr/local/var/www/app/public:/app:rw'
nginx:
  image: 'fatrbaby/nginx'
  ports:
    - '8090:80'
  links:
    - 'php:php-fpm'
  volumes:
    - '/usr/local/var/www/app/public:/app:rw'

