version: '2'
services:
  php:
    image: 'fatrbaby/php7'
    container_name: php
    volumes:
      - '/usr/local/var/www/app/public:/app:rw'
  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    ports:
      - '8090:80'
    links:
      - 'php:php-fpm'
    volumes:
      - '/usr/local/var/www/app/public:/app:rw'
      - './etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - './etc/redis.conf:/etc/redis.conf'
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - '/usr/local/var/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  golang:
    image: golang:1.8-alpine
    container_name: golang
