version: '3'
services:
  fluentd:
    image: fluent/fluentd:v0.14
    container_name: fluentd
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    volumes:
      - '/usr/local/var/fluentd:/fluentd/log'
      - './etc/fluentd:/fluentd/etc'
    environment:
      FLUENTD_CONF: fluentd.conf
