version: '2'
services:
  php:
    build: './images/php'
    container_name: php
    volumes:
      - '/usr/local/var/www/app/public:/app:rw'
  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    ports:
      - '8090:80'
    links:
      - 'php:php-fpm'
    volumes:
      - '/usr/local/var/www/app/public:/app:rw'
      - './etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
