version: 3
services:
  registry:
    image: registry
    containser_name: registry
    restart: always
    volumns:
      - "/var/local/var/registry:/var/lib/registry"
      - "./etc/registry/config.yml:/etc/docker/registry/config.yml"
    ports:
      - "5000:5000"
