version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - '/usr/local/var/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - './etc/redis.conf:/etc/redis.conf'